package com.example.recaptcha.exception;

import java.lang.System;

@kotlin.Metadata(mv = {1, 5, 1}, k = 1, d1 = {"\u0000\u0014\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\b\u00c6\u0002\u0018\u00002\u00020\u0001B\u0007\b\u0002\u00a2\u0006\u0002\u0010\u0002J\u0010\u0010\u0003\u001a\u00020\u00042\b\u0010\u0005\u001a\u0004\u0018\u00010\u0001\u00a8\u0006\u0006"}, d2 = {"Lcom/example/recaptcha/exception/RestExceptionFactory;", "", "()V", "checkErrorList", "", "error", "recaptcha_debug"})
public final class RestExceptionFactory {
    @org.jetbrains.annotations.NotNull()
    public static final com.example.recaptcha.exception.RestExceptionFactory INSTANCE = null;
    
    private RestExceptionFactory() {
        super();
    }
    
    public final void checkErrorList(@org.jetbrains.annotations.Nullable()
    java.lang.Object error) {
    }
}